[portal] Update portal to 0.2.2
cloudposse-archives/helmfiles pull request #14
Opened 2018-08-05 06:20 UTC by osterman

## what
* Upgrade portal to `0.2.2`
* Deprecate endpoint as no longer used
* Introduce `externalName`
* Support `path` parameter

## why
* Previous portal relied on a custom traefik implementation
* This uses native ingress
* Support paths for kibana

## upgrading
* All previous `*_ENDPOINT` envs are deprecated
* Use `..._SERVICE_NAME`, `.._SERVICE_PORT` and `..._EXTERNAL_NAME` instead

## references
- <https://github.com/cloudposse/charts/pull/152>
- <https://github.com/cloudposse/geodesic/issues/191>

2018-08-05 06:20 UTC, osterman commented
Depends on https://github.com/cloudposse/charts/pull/152

2018-08-06 14:06 UTC, aknysh submitted a review, later dismissed

2018-08-07 13:13 UTC, alebabai submitted a review, later dismissed

2018-08-07 16:33 UTC, goruha requested changes

2018-08-07 16:33 UTC, goruha commented on helmfile.d/0620.portal.yaml
> +  url: "https://charts.dev.cloudposse.com/fix/gh151/portal-url-paths/incubator/"
Why we should reference dev repo?

2018-09-05 19:43 UTC, goruha submitted a review, later dismissed

2018-09-05 19:44 UTC, goruha approved these changes

2018-09-05 19:51 UTC, merged