[stable-nginx-ingress] Change release name for `stable-nginx-ingress` chart
cloudposse-archives/helmfiles pull request #28
Opened 2018-08-14 19:50 UTC by aknysh

## what
* Change release name for `stable-nginx-ingress` chart

## why
* To be able to deploy charts by the release name, e.g. `helmfile --selector name=stable-ingress` when we have multiple helmfiles for the same chart

2018-08-14 21:08 UTC, osterman commented on helmfile.d/0330.stable-nginx-ingress.yaml
> +- name: "stable-ingress"
I don't think this is any more scalable a strategy. 

I think better to just use a better selector. That said, I think we may need to add a label to better disambiguate it. 

Perhaps, add a label for `repo` or `repository`

2018-08-14 21:08 UTC, osterman commented on helmfile.d/0330.stable-nginx-ingress.yaml
> +- name: "stable-ingress"
In this case it would be `--selector name=ingress,repo=stable`

2018-08-14 21:08 UTC, osterman commented on helmfile.d/0330.stable-nginx-ingress.yaml
> +- name: "stable-ingress"
or `--selector name=ingress,repo=cloudposse-incubator`

2018-08-14 21:09 UTC, osterman commented on helmfile.d/0330.stable-nginx-ingress.yaml
> +- name: "stable-ingress"
It's better to keep release names as short as possible to reduce pod name length and avoid trucnation.

2018-08-15 08:40 UTC, alebabai requested changes

2018-08-15 08:40 UTC, alebabai commented on helmfile.d/0110.kube-lego.yaml
> +    repo: "stable"
Here is `cloudposse-incubator` repo, not `stable` one

2018-08-15 12:07 UTC, alebabai approved these changes

2018-08-15 16:05 UTC, merged