[fluentd-elasticsearch] Add helmfile for the official `fluentd-elasticsearch` chart
cloudposse-archives/helmfiles pull request #30
Opened 2018-08-20 19:02 UTC by aknysh

## what
* Add `helmfile` for the official `fluentd-elasticsearch` chart

## why
* [stable/fluentd-elasticsearch](https://github.com/helm/charts/tree/master/stable/fluentd-elasticsearch) is the official chart for Installing Fluentd log forwarder for Elasticsearch
* Released from `incubator` to `stable`

2018-08-20 19:03 UTC, osterman commented on helmfile.d/0530.fluentd-elasticsearch.yaml
> +      name:
Parameterize

2018-08-20 19:04 UTC, osterman requested changes
One small nitpick. Otherwise LGTM

2018-08-20 19:32 UTC, osterman submitted a review, later dismissed

2018-08-22 00:39 UTC, osterman requested changes
Decompose into 2 PRs. One per helmfile.

2018-08-22 00:40 UTC, osterman commented on helmfile.d/0520.fluentd-elasticsearch-logs.yaml
> +#      secret:
Add a conditional rather than comment out. Customer may be using a managed ES in the future.

2018-08-22 11:27 UTC, goruha commented
Update
* Fluentd from stable repo - removed
* Reverted user/password env vars

Anything else for merge?

2018-08-22 15:07 UTC, osterman approved these changes

2018-08-22 15:10 UTC, merged