Add stable/grafana helmfile
cloudposse-archives/helmfiles pull request #4
Opened 2018-08-02 07:04 UTC by alebabai

## what
* add helmfile with stable/grafana chart
* add values with examples how to add custom dashboards (for stable/grafana and kube-prometheus/grafana)
 
## why
* Dashboards import is unclear for now with default kube-prometheus grafana deployment

2018-08-02 19:19 UTC, osterman commented on helmfile.d/0420.grafana.yaml
> +    - "--recreate-pods"
Drop this as it causes outages.

2018-08-02 19:21 UTC, osterman commented on helmfile.d/0410.kube-prometheus.yaml
>          rbacEnable: false
Make this an env.

2018-08-02 19:21 UTC, osterman requested changes
See comments.

2018-08-02 19:27 UTC, osterman commented on helmfile.d/0420.grafana.yaml
> +    - "--recreate-pods"
Drop this as it causes outages.

2018-08-02 20:53 UTC, aknysh commented on helmfile.d/0420.grafana.yaml
> +    default: "true"
default: "false"

2018-08-02 20:58 UTC, aknysh commented on helmfile.d/0420.grafana.yaml
> +              url: 'http://kube-prometheus-prometheus:9090'
make it a variable:
url:  {{ env "GRAFANA_PROMETHEUS_ENDPOINT" | default "http://kube-prometheus-prometheus:9090" }}'

2018-08-02 21:00 UTC, aknysh commented
add this section:

```

serviceAccount:
  create: true
  name:

```

Make `create` and `name` variables
https://github.com/helm/charts/blob/master/stable/grafana/values.yaml#L4

2018-08-02 21:04 UTC, aknysh commented
add `ingress` section similar to this:

```

ingress:
      enabled: {{ env "GRAFANA_INGRESS_ENABLED" | default "false" }}
      annotations:
        kubernetes.io/ingress.class: "nginx"
        kubernetes.io/tls-acme: "true"
        external-dns.alpha.kubernetes.io/ttl: "60"
        external-dns.alpha.kubernetes.io/target: {{ env "GRAFANA_INGRESS" }}
        external-dns.alpha.kubernetes.io/hostname: {{ env "GRAFANA_HOSTNAME" }}
      hosts:
      - {{ env "GRAFANA_HOSTNAME" }}
      tls:
      - secretName: {{ env "GRAFANA_SECRET_NAME" | default "grafana-server-tls" }}
        hosts:
        - {{ env "GRAFANA_HOSTNAME" }}

```

2018-08-02 21:05 UTC, aknysh commented on helmfile.d/0420.grafana.yaml
> +    - persistence:
make it a variable

2018-08-02 21:06 UTC, aknysh commented on helmfile.d/0420.grafana.yaml
> +        size: 10Gi
make `size` a variable

2018-08-02 21:07 UTC, aknysh submitted a review, later dismissed
inline comments

2018-08-03 05:03 UTC, osterman commented
This will fix CI: https://github.com/cloudposse/helmfiles/pull/7

2018-08-03 07:34 UTC, alebabai commented on helmfile.d/0420.grafana.yaml
> +    - "--recreate-pods"
did you mean only "--recreate-pods" or both?

2018-08-03 08:58 UTC, osterman approved these changes

2018-08-03 08:58 UTC, merged