[WIP] ALB Cognito
cloudposse-archives/helmfiles pull request #69
Opened 2018-12-27 17:57 UTC by goruha

2019-01-08 01:18 UTC, osterman submitted a review, later dismissed
Drop ordinal prefix of helmfile

2019-02-13 18:57 UTC, tamsky commented on helmfiles/aws-alb-ingress.yaml
> +      repository: m00nf1sh/aws-alb-ingress-controller
Looks like this was merged in:
https://github.com/kubernetes-sigs/aws-alb-ingress-controller/pull/754
and this should be updated to:
`docker.io/amazon/aws-alb-ingress-controller:v1.1.1`

2019-02-13 19:10 UTC, tamsky commented
`    alb.ingress.kubernetes.io/certificate-arn: 	arn:aws:acm:us-west-2:126450723953:certificate/2e2e7768-ef18-450d-87d9-20b8ffa65655`
currently hardcoded
would prefer using ACM to generate -- or caller uses a data source?

2019-02-13 19:12 UTC, tamsky commented
un-hardcode:
`"SecretName":"odic-secret"`
which references
```
apiVersion: v1
kind: Secret
metadata:
  namespace: testcase
  name: odic-secret <<<<
data:
  clientId: XXXX
  clientSecret: XXXX
```

2019-02-15 00:20 UTC, tamsky requested changes

2019-02-15 00:20 UTC, tamsky commented on helmfiles/aws-alb-ingress.yaml
> +  - clusterName: us-west-2.testing.cloudposse.co
need to templatize
eg `'{{ env "ATLANTIS_IMAGE" | default "runatlantis/atlantis" }}'`

2019-02-15 00:20 UTC, tamsky commented on helmfiles/aws-alb-ingress.yaml
> +      iam.amazonaws.com/role: cpco-testing-alb-ingress
will replace with templated value, similar to
`'{{ env "ALB_INGRESS_IAM_ROLE" }}'`

2019-02-15 00:20 UTC, tamsky commented on helmfiles/aws-alb-ingress.yaml
> +      # limits:
add configurable resource limits, and defaults
like
https://github.com/cloudposse/helmfiles/blob/14a8209084327fe5fb83d5cc33a2dca67cf38c69/releases/external-dns.yaml#L50-L55

2019-02-15 00:20 UTC, tamsky commented on helmfiles/aws-alb-ingress.yaml
> +      create: true
use shared/common RBAC enablement var:
`create: {{ env "RBAC_ENABLED" | default "false" }}`

2019-02-15 00:20 UTC, tamsky commented on helmfiles/aws-alb-ingress.yaml
> +repositories:
helm files have a function `requireEnv` instead of `env`
in helm files we can use both.
it is still in discussion how/if we should use `require` or not.

2019-02-15 00:20 UTC, tamsky commented on helmfiles/aws-alb-ingress.yaml
> +      ingressClass: alb
make this class name configurable
`{{ env "ALB_INGRESS_CLASS_NAME" | default "alb" }}`

2019-02-15 08:24 UTC, tamsky commented on helmfiles/aws-alb-ingress.yaml
> +      repository: m00nf1sh/aws-alb-ingress-controller
Resolved in https://github.com/cloudposse/helmfiles/pull/86/commits/48c3ab984b1454b0f0025719aaa9c1beaac74f9c

2019-02-15 08:45 UTC, tamsky commented on helmfiles/aws-alb-ingress.yaml
> +  - clusterName: us-west-2.testing.cloudposse.co
fixed in https://github.com/cloudposse/helmfiles/pull/86/commits/cf839d24ce7ae249fa34d1694f6264afbb75f709

2019-02-15 09:18 UTC, tamsky commented on helmfiles/aws-alb-ingress.yaml
> +      iam.amazonaws.com/role: cpco-testing-alb-ingress
fixed in https://github.com/cloudposse/helmfiles/pull/86/commits/3077ccece56f9f449c48df9c56f5162c824e49f6

2019-02-15 09:18 UTC, tamsky commented on helmfiles/aws-alb-ingress.yaml
> +      # limits:
https://github.com/cloudposse/helmfiles/pull/86/commits/fb494378e0785abaa9db4a4a5bc7753f25d92264

2019-02-15 09:25 UTC, tamsky commented on helmfiles/aws-alb-ingress.yaml
> +repositories:
@osterman is use of the`| required` function still undecided ?

2019-02-15 09:28 UTC, tamsky commented on helmfiles/aws-alb-ingress.yaml
> +      ingressClass: alb
fixed in https://github.com/cloudposse/helmfiles/pull/86/commits/cef723aa09a48a7b24cd7f438e53f5d59fc87c1e

2019-02-15 09:30 UTC, tamsky commented on helmfiles/aws-alb-ingress.yaml
> +      create: true
fixed in https://github.com/cloudposse/helmfiles/pull/86/commits/2eb8d822a9d5a637d513308e402ef84110c6688e

2019-02-20 19:29 UTC, tamsky commented
> in the example helmfile (found in this PR's description), we should un-hardcode:
> `"SecretName":"odic-secret"`
> which references
> 
> ```
> apiVersion: v1
> kind: Secret
> metadata:
>   namespace: testcase
>   name: odic-secret <<<<
> data:
>   clientId: XXXX
>   clientSecret: XXXX
> ```

I've updated the PR description, correcting presumed typo `odic-secret` -> `oidc-secret`
@goruha can you confirm this was a typo?

2019-02-28 04:16 UTC, tamsky commented
Answering my own questions above:

* The example kubectl file that is this PR's #Example is fine with hardcoded `arn:aws:acm`.
No additional ACM work is required here.

* The example hardcoded secrets are also fine.

2019-03-10 00:33 UTC, tamsky approved these changes
LGTM, but would like someone else to review.

2019-03-10 04:41 UTC, osterman approved these changes

2019-03-18 00:49 UTC, merged