Rename `helmfiles` to `releases`
cloudposse-archives/helmfiles pull request #76
Opened 2019-01-10 11:04 UTC by goruha

## What
* Rename `helmfiles` to `releases`

## Why
* Naming dir `helmfiles` was a mistake.

2019-01-10 19:54 UTC, aknysh commented on README.yaml
> +  COPY --from helmfiles /helmfiles /conf/helmfiles/
```suggestion
  COPY --from=helmfiles /helmfiles /conf/helmfiles/
```

2019-01-10 19:55 UTC, aknysh reviewed
see comments

2019-01-11 02:11 UTC, osterman approved these changes

2019-01-11 02:12 UTC, osterman commented on README.yaml
> +  COPY --from helmfiles /helmfiles /conf/helmfiles/
```suggestion
  COPY --from=helmfiles /helmfiles/ /conf/helmfiles/
```

2019-01-11 02:13 UTC, osterman requested changes
See comments

2019-01-14 10:22 UTC, osterman approved these changes

2019-01-14 10:30 UTC, merged